{{- if .Values.configMap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spring-cubix-cn.fullname" . }}
  labels:
    {{- include "spring-cubix-cn.labels" . | nindent 4 }}
data:
  application.properties: |-
    spring.main.banner-mode=off
    target.api.url=http://appb:8080
    spring.application.name=appa
{{- end }}