apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-cubix-cn.fullname" . }}
  labels:
    {{- include "spring-cubix-cn.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
  selector:
    {{- include "spring-cubix-cn.selectorLabels" . | nindent 4 }}
